### ISSUE TITLE
preventDuplicates enhancement to restart "showDuration" & "extendedTimeOut" etc.

### ISSUE THREAD

**Issue by nevf** [CodeSeven/toastr#288] opened 2015-05-25 02:11 UTC
I'd like to have a way for ```preventDuplicates``` to restart ```showDuration``` & ```extendedTimeOut```. 

At present when you pass in these options, they are ignored when a duplicate toast is already displayed. This mean when a toast is near the end of it's ```showDuration``` and you call it again to display a duplicate, the later will quickly disappear. This is especially troublesome when the toast requires the user to click it to perform some action, as they don't get a chance.

**Comment by TimFerrell** [comment] 2015-05-25 02:24
Is this a duplicate of #287?

**Comment by nevf** [comment] 2015-05-25 04:09
@TimFerrell No it is a different issue.

**Comment by nevf** [comment] 2015-05-25 05:48
@TimFerrell Please see http://clibu.com/public_files/toast2.html and view console output. settimeout() is to fake the user doing something to open the second toast.

Source is:
````
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <style>
       /* Set font for toastr */
      .toast{
         font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
         font-size: 14px;
      }
    </style>
  </head>

  <body>

    <script>

      function undo_toast( prop ){
        console.log( "prop", prop );
        toastr.warning( "Undo", "", { "showDuration": "6000", "extendedTimeOut": 5000, "preventDuplicates": true, });
     }

     undo_toast( "test1" );
     setTimeout( function(){
        undo_toast( "test2 - closes in .5 sec" );      // this will close in .5 sec. I want "showDuration" & "extendedTimeOut" to restart now.
     }, 4500 );

    </script>

  </body>
</html>
````

**Comment by TimFerrell** [comment] 2016-07-07 17:55
Will keep this suggestion in mind for v3. Nothing actionable for now.

**Closed by TimFerrell** 2016-07-07 17:55 UTC
