### ISSUE TITLE
npm install is installing 2.0.3 instead of 2.1.0

### ISSUE THREAD

**Issue by mark0978** [CodeSeven/toastr#247] opened 2015-02-16 15:51 UTC
$ npm list
toastr@2.0.4 /tmp/node_modules/toastr
└── (empty)

The toastr.js file reads like this:
```
/*
 * Toastr
 * Copyright 2012-2014 John Papa and Hans Fjällemark.
 * All Rights Reserved.
 * Use, reproduction, distribution, and modification of this code is subject to the terms and
 * conditions of the MIT license, available at http://www.opensource.org/licenses/mit-license.php
 *
 * Author: John Papa and Hans Fjällemark
 * ARIA Support: Greta Krafsig
 * Project: https://github.com/CodeSeven/toastr
 */
...
                version: '2.0.3',
                warning: warning
            };

```

**Comment by TimFerrell** [comment] 2015-02-16 17:08
Version 2.1.0 is not yet available outside of GitHub. 

@johnpapa - there have been a few requests about this. What do you say that we push 2.1.0 out, and resume development work exclusively under the develop branch as we'd planned? This should be the last push to make that happen.

**Comment by TimFerrell** [comment] 2015-02-16 17:10
Also, it looks like NuGet got the update to 2.1.0 but npm didn't.

**Comment by johnpapa** [comment] 2015-02-18 12:45
Are we publishing on npm? If we are, we need to add that to the checklist md for release. I'm cool with that.

**Comment by mark0978** [comment] 2015-02-18 14:49
Not sure how to read this.  The issue is closed, but npm didn't get updated.  Does this mean you are no longer publishing on npm?  Checklist.md isn't updated to reflect this either.

**Comment by mark0978** [comment] 2015-02-23 17:07
Does this mean you are no longer publishing to npm?  Only to Microsoft's NuGet?

**Comment by TimFerrell** [comment] 2015-02-23 17:41
I'm good with pushing up to npm. We just merged up develop into master, so the push of this release out should hit everywhere else shortly.
@johnpapa  - any issues here?

**Comment by TimFerrell** [comment] 2015-03-13 04:13
@durango - it appears that you own the NPM repo. Any chance of getting it updated to 2.1.1?

**Comment by nkoterba** [comment] 2015-06-16 21:44
@TimFerrell @durango

Any update on this?  We are using npm with Browserify and CommonJS syntax and right now Toastr is still on version 2.0.4 on NPM.

I tried using the "preventDuplicates" option but that's not even in the source code or available in the current npm version.

Thanks!

**Comment by mark0978** [comment] 2015-06-16 23:24
I think John papa has gone over to the dark side.  MS is strong with him.

**Comment by TimFerrell** [comment] 2015-06-16 23:29
If someone can get a hold of @durango then we might be able to get this updated. If not, we can look into getting another package added to npm.

**Comment by nkoterba** [comment] 2015-06-16 23:30
@mark0978 hahaha.

I will say it's hard/tedious updating/maintaining any package these days because you need:
* Github
* NPM
* Bower
* Nuget
* CDN
* ...

**sigh**

MS is actually encouraging/using NPM in Visual Studio 2015 and future web projects (though I think they prefer Bower at the moment over NPM).  

I don't think it's too hard to update NPM with the latest toastr it's just a matter of getting this issue visible again and getting the right person with the right NPM permissions to hopefully find some free time...

In the meantime I may try the *bower* version.  

We have also looked into using JSPM...one of the other libraries we were using didn't play nicely with it due to a bug but depending on your size/project it allows to pull directly from github.

**Comment by TimFerrell** [comment] 2015-06-16 23:33
Is there a tool that can push out to multiple package managers given a tag in git? Pushing out now is not fun.

**Comment by johnpapa** [comment] 2015-06-16 23:36
I believe future we'll support npm and bower, moving forward. No more NuGet and maybe no CDN.

**Comment by nkoterba** [comment] 2015-06-16 23:39
So there's no tool I know of that will publish to multiple sources/repos/etc.

Thought such a tool sounds quite handy especially if it was updated and maintained to support the latest "popular" options.

However, I notice toastr is using **gulp** so it would be easy enough to write a few gulp tasks that would push toastr up to npm, bower, and nuget.

Here is an example using grunt but I believe similar packages are available for gulp: http://liddellj.com/publishing-to-bower-npm-and-nuget-using-grunt/

@johnpapa Yes I heard that MSFT is encouraging using Bower/NPM for front-end libraries and Nuget for the more traditional server-side/application libraries.

Although we have moved away from using CDNs, they still seem popular and have some benefits over loading everything locally or bundled, especially for extremely common packages (e.g. jquery, angular, etc.)

**Comment by durango** [comment] 2015-06-17 10:21
@TimFerrell are you not listed as the npm owner for this package? I was under the impression that you were and that I was removed.

**Comment by durango** [comment] 2015-06-17 10:24
Ah now I see that's not the case :) I .. haven't received any emails from anyone @TimFerrell what's your npm username?

**Comment by TimFerrell** [comment] 2015-06-17 14:42
@durango TimFerrell

**Comment by durango** [comment] 2015-06-17 14:55
@TimFerrell

**Comment by TimFerrell** [comment] 2015-06-17 15:00
@durango  - @timferrell is my npm username.

**Comment by durango** [comment] 2015-06-17 15:02
Ah yeah casing matters hah.. anyway

```
λ MacBook-Pro toastr-real → λ git master → npm owner add timferrell
+ timferrell (toastr)
```

**Comment by TimFerrell** [comment] 2015-06-17 15:05
Confirmed - thanks.

**Comment by jimf** [comment] 2015-06-22 19:16
+1 on getting the latest stabile build on npm, as well as deprecating NuGet.

**Comment by TimFerrell** [comment] 2015-06-29 04:07
npm updated to 2.1.0 - will await confirmation before closing.

![screen shot 2015-06-29 at 12 06 56 am](https://cloud.githubusercontent.com/assets/189421/8400831/c68c64ec-1df2-11e5-866a-df852433dc43.png)

**Comment by skeletalbassman** [comment] 2015-06-29 04:10
Confirmed npm updated to version 2.1.0

![image](https://cloud.githubusercontent.com/assets/8602025/8400857/17aebee2-1dda-11e5-93f2-5d00b5b68501.png)

**Comment by TimFerrell** [comment] 2015-06-29 04:10
Thanks for the confirmation, @skeletalbassman.

**Closed by TimFerrell** 2015-06-29 04:10 UTC
Labels: question

**Comment by jimf** [comment] 2015-06-29 12:25
Thanks all! :beers:

**Comment by nkoterba** [comment] 2015-07-31 21:09
@TimFerrell Any chance to get the NPM repo updated to 2.1.1?

It seems NPM was once again left behind bower =(

**Comment by TimFerrell** [comment] 2015-08-05 12:35
@nkoterba  - will take a look into getting it updated again. NPM was giving me big issues with their cache last time.

**Comment by TimFerrell** [comment] 2015-08-10 03:12
@nkoterba - 2.1.2 is up in NPM - that work for you?

**Comment by nkoterba** [comment] 2015-08-10 14:52
@TimFerrell Looks great! Thanks!

I keep hoping we can move to just one package manager (npm) since we do a lot of `gulp` stuff during our UI build process, but I get the feeling `bower` isn't going away anytime soon and seems to get UI-lib updates more often.
