### ISSUE TITLE
preventDuplicates enhancement to keep most recent toast.

### ISSUE THREAD

**Issue by nevf** [CodeSeven/toastr#287] opened 2015-05-25 00:47 UTC
I need to use ```"preventDuplicates": true``` with an "Undo" toast plus onclick callback, so only one "Undo" toast is ever displayed. However I need the most recent toast to be active, not the existing one. This is so variable in the callback closure is the most recent one, not the previous one.

I tried using ```toastr.clear()``` but that looks odd as you ```hideDuration``` delays the toast for clearing. The parameters for ```toastr.clear()``` are undocumented, and adding ```hideDuration``` as ```clearOptions``` of course doesn't do anything.

Also if you call  ```toastr.clear()``` and then use display a duplicate toast with ```"preventDuplicates": true``` it is displayed briefly and then hidden. 

I hope that all makes sense.

**Comment by TimFerrell** [comment] 2015-05-25 02:23
Can you please link to an example?

**Comment by nevf** [comment] 2015-05-25 05:37
@TimFerrell Please see: http://clibu.com/public_files/toast1.html which is:

````
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <style>
       /* Set font for toastr */
      .toast{
         font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
         font-size: 14px;
      }
    </style>
  </head>

  <body>

    <script>

      function undo_toast( prop ){
        toastr.warning( "Undo", "", { "preventDuplicates": true, "onclick": function(){
                console.log( 'Undo', prop );     // => "test1" but I want "test2"
            }
        });
     }

     undo_toast( "test1" );
     undo_toast( "test2" );
    
    </script>

  </body>
</html>
````

**Comment by TimFerrell** [comment] 2015-05-25 18:54
I think I understand what you're saying. However, if a toast is determined to be a duplicate of the previous toast, then the toast is never created, so there is no way to reference it. 
Take a look at [this line of code] (https://github.com/CodeSeven/toastr/blob/master/toastr.js#L339). If you want the `previousToast` to be the most recent duplicate, you can modify the function to do so here. Just do it before the return true statement.

**Comment by TimFerrell** [comment] 2015-05-25 18:54
Also, if you need to immediately remove all toasts without any animations, you can do so via the `toastr.remove()` function.

**Comment by nevf** [comment] 2015-05-26 21:39
@TimFerrell Thanks I'll have a look at the code. And ```toastr.remove()``` could be useful. For now I've put a work-around in my code.

That said https://github.com/CodeSeven/toastr/issues/288 is a more pressing issue. I assume that resolving that will also resolve this.

**Comment by TimFerrell** [comment] 2015-10-10 01:39
Reasonable workaround is in place. Focusing on v3.

**Closed by TimFerrell** 2015-10-10 01:39 UTC
