### ISSUE TITLE
2.1.3 is not in npm

### ISSUE THREAD

**Issue by rmadamanchi** [CodeSeven/toastr#541] opened 2017-10-02 14:31 UTC
http://registry.npmjs.com/toastr

Is there a plan to publish 2.1.3 to npm?

**Comment by burtyish** [comment] 2017-10-18 10:11
Duplicate of #450

**Comment by pompex** [comment] 2017-10-18 16:36
This project is so dead.

**Comment by xemasiv** [comment] 2017-10-31 04:40
Any updates on this? Anyone maintaining a forked branch?

**Comment by Pysis868** [comment] 2017-11-19 01:33
Almost missed the neat suggestions mentioned in #450, notably some `package.json` customizations, and some forks that GitHub would not report when I checked the Insights tab, Forks section, saying something about having a lot of networks to browse, so only reporting a portion of them, but then finding no results there...

It would be too bad if NPM really doesn't let you re-publish packages like that, but I don't know much about it.

**Comment by TimFerrell** [comment] 2017-12-08 03:22
I just pushed `2.1.4`, which is the same as `2.1.3` except for the tag: https://www.npmjs.com/package/toastr

**Closed by TimFerrell** 2017-12-08 03:22 UTC
