### ISSUE TITLE
With  timeOut=0, .clear() does not do anything

### ISSUE THREAD

**Issue by mirko77** [CodeSeven/toastr#498] opened 2017-01-31 11:40 UTC
I noticed if you set a toast with timeOut = 0 i.e you do not want to hide it after x secs, calling .clear() does not clear the toasts.

Looking at the source:

```

hideToast: function hideToast(override) {
    if (this.isHiding || this.intervalId === null && !override) {
      return;
    }

    this._set_is_hiding(true);
    if (this.props.transition) {
      this._set_transition(true);
    } else if (this.props.hideAnimation) {
      this._set_animation(true);
    } else {
      this._handle_remove();
    }
  }

```

the `this.intervalId === null` stops the toasts from being hidden.

Is this done on purpse?

I would expect .clear() to work regardless...The only solution is to set a very long timeout.

**Comment by grantiverson** [comment] 2018-06-15 06:06
@TimFerrell Recommend closing. Could not reproduce the issue.

**Comment by TimFerrell** [comment] 2018-06-15 13:14
Thanks @grantiverson.

**Closed by TimFerrell** 2018-06-15 13:14 UTC
