### ISSUE TITLE
Toasts prevent clicking of background elements

### ISSUE THREAD

**Issue by leniel** [CodeSeven/toastr#235] opened 2015-01-09 14:37 UTC
The way it is now, the menu behind the toast is unclickable.

The following style complements it and fixes the issue. Just add it to your own .css file or in the future it could make it into a new toastr version. :)

``` css
.toast-top-center
{
    width: 300px;
    margin: 0 auto;
    left: 0;
}
```

**Comment by jeffijoe** [comment] 2015-03-09 08:21
Had the same issue, I fixed it like this:

```less
#toast-container {
  pointer-events: none;
  > div {
    pointer-events: auto;
  }
}
```

**Comment by TimFerrell** [comment] 2015-03-25 01:59
Can you please demo what the exact issue is?

**Comment by jeffijoe** [comment] 2015-03-25 07:47
@TimFerrell I just did one. Instructions are pretty simple. Show the toast, and afterwards (while the toast is showing) try to click the button.

http://jsfiddle.net/jeffijoe/x5mgoqb2/2/

**Comment by TimFerrell** [comment] 2015-03-27 13:33
Can't accept this as-is. The CSS provided prevents the closeButton option from working, and prevents any clickable content within the toast from being activated. 

See fiddle: https://jsfiddle.net/jeffijoe/x5mgoqb2/2/

**Comment by TimFerrell** [comment] 2015-04-01 16:42
Closing this as it would break existing functionality. If anyone cares to dig more deeply into this and provide a solution that does not break anything I'd be interested in reviewing it.

**Comment by nikatlas** [comment] 2015-04-24 08:23
I suggest re considering the @leniel 's  solution it doesnt seem to break my functionality niether any clickable area. 

@leniel 's css
.toast-top-center
{
    width: 300px;
    margin: 0 auto;
    left: 0;
}

**Comment by nevf** [comment] 2015-09-28 01:51
+1 for @leniel fix. This is a major problem as it breaks all clickable elements which are on the same row as a toast.

**Comment by TimFerrell** [comment] 2015-09-28 01:59
Isn't this issue fixed with this line here? https://github.com/CodeSeven/toastr/blob/master/build/toastr.css#L98

**Comment by nevf** [comment] 2015-09-28 20:36
No that doesn't help at all, at least not on Chrome. MDN says:
pointer-events: auto; "The element behaves as it would if the pointer-events property were not specified." ref: https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

**Comment by TimFerrell** [comment] 2015-10-10 02:00
Under reconsideration.

**Comment by masious** [comment] 2016-02-28 13:15
Same issue here. toast-container takes about all of the width of the page, and consumes all the click events without triggering them for the items beneath.

**Comment by Alicia-L** [comment] 2017-03-23 14:45
+1 for @leniel fix. As @nevf says, this breaks all clickable elements which are on the same row as a toast. Many applications (such as mine) have a navigation bar on top, and a 'toast-top-center' will overlap with it. This will render all the buttons on the navbar unclickable, even if they're visible and the user thinks he should be able to click them, since as far as they can tell the toast shouldn't interfere.

**Comment by grantiverson** [comment] 2018-06-13 04:54
@TimFerrell I could not reproduce the issue. Perhaps this was fixed with 2.1.3.

**Comment by TimFerrell** [comment] 2018-06-14 12:33
Thanks for confirming @grantiverson. Closing, but please re-open if necessary.

**Closed by TimFerrell** 2018-06-14 12:33 UTC
Labels: wontfix

**Comment by galvarez421** [comment] 2019-09-16 19:06
The fix in https://github.com/CodeSeven/toastr/pull/269 was not incorporated into the Sass file.

**Comment by rmunoz10** [comment] 2020-10-15 01:31
Still an issue in latest version
